# Generated by Django 4.1.5 on 2023-01-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billId", models.CharField(max_length=10, unique=True)),
                ("memberId", models.CharField(max_length=10)),
                ("totalMoney", models.IntegerField()),
                ("cbTax", models.FloatField()),
                ("cbPoint", models.FloatField()),
                ("cbEm", models.FloatField()),
                ("billDt", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("memberId", models.CharField(max_length=10, unique=True)),
                ("memberAc", models.CharField(max_length=10)),
                ("memberPw", models.CharField(max_length=15)),
                ("memberName", models.TextField(max_length=15)),
                ("create", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "member",
            },
        ),
    ]
