# Generated by Django 4.1.5 on 2023-01-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bill",
            table="bill",
        ),
    ]
