# Generated by Django 4.1.5 on 2023-01-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_bill_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="memberAdr",
            field=models.TextField(default="", max_length=25),
        ),
        migrations.AddField(
            model_name="member",
            name="memberEml",
            field=models.TextField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="member",
            name="memberTel",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="member",
            name="memberId",
            field=models.CharField(auto_created=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="memberName",
            field=models.TextField(default="", max_length=15),
        ),
    ]
