# Generated by Django 4.1.5 on 2023-01-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_member_memberadr_member_membereml_member_membertel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="memberId",
        ),
    ]
