# Generated by Django 4.1.5 on 2023-01-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_member_memberpt"),
    ]

    operations = [
        migrations.CreateModel(
            name="car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("memberAc", models.CharField(default="", max_length=10)),
                ("carName", models.CharField(default="", max_length=10)),
                ("carImg", models.CharField(default="", max_length=15)),
                ("carNum", models.CharField(default="", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="consume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("memberAc", models.CharField(default="", max_length=10)),
                ("carName", models.CharField(default="", max_length=10)),
                ("carImg", models.CharField(default="", max_length=15)),
                ("carNum", models.CharField(default="", max_length=10)),
                ("starttime", models.TimeField(auto_now=True)),
                ("endtime", models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
