# Generated by Django 4.1.5 on 2023-01-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_car_table_alter_consume_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="carEv",
            field=models.ImageField(default=0, upload_to=""),
        ),
    ]
