# Generated by Django 4.1.5 on 2023-01-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_car_carev"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consume",
            name="endtime",
        ),
        migrations.AddField(
            model_name="consume",
            name="usePt",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="consume",
            name="useSec",
            field=models.IntegerField(default=0),
        ),
    ]
