# Generated by Django 4.1.5 on 2023-01-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_remove_consume_endtime_consume_usept_consume_usesec"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consume",
            name="carImg",
        ),
    ]
