# Generated by Django 4.1.5 on 2023-01-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_remove_consume_carimg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consume",
            name="starttime",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
