# Generated by Django 4.1.5 on 2023-01-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_consume_starttime"),
    ]

    operations = [
        migrations.CreateModel(
            name="shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("href", models.CharField(default="", max_length=20)),
                ("shopimg", models.CharField(default="", max_length=20)),
                ("shopName", models.CharField(default="", max_length=20)),
            ],
            options={
                "db_table": "shop",
            },
        ),
    ]
