# Generated by Django 4.1.5 on 2023-01-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_shop"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="shop",
            new_name="myshop",
        ),
        migrations.AlterModelTable(
            name="myshop",
            table="myshop",
        ),
    ]
