# Generated by Django 4.1.5 on 2023-01-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_rename_shop_myshop_alter_myshop_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="consume",
            name="consumeName",
            field=models.CharField(default="", max_length=15),
        ),
    ]
