# Generated by Django 4.1.5 on 2023-01-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_consume_consumename"),
    ]

    operations = [
        migrations.AddField(
            model_name="consume",
            name="piece",
            field=models.IntegerField(default=0),
        ),
    ]
