# Generated by Django 4.1.5 on 2023-01-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_friend"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friend",
            name="friendAc",
        ),
        migrations.AddField(
            model_name="friend",
            name="friendTel",
            field=models.CharField(default="", max_length=10),
        ),
    ]
