# Generated by Django 4.1.5 on 2023-01-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_remove_friend_friendac_friend_friendtel"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="friendName",
            field=models.TextField(default="", max_length=15),
        ),
    ]
