# Generated by Django 4.1.5 on 2023-01-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_friend_friendname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="carImg",
            field=models.CharField(default="", max_length=25),
        ),
    ]
