# Generated by Django 4.1.5 on 2023-01-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_alter_car_carimg"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="carbrand",
            field=models.CharField(default="", max_length=15),
        ),
    ]
