# Generated by Django 4.1.5 on 2023-01-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_car_carbrand"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="friendImg",
            field=models.CharField(default="", max_length=20),
        ),
    ]
