# Generated by Django 4.1.5 on 2023-01-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_friend_friendimg"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="memberImg",
            field=models.CharField(default="", max_length=20),
        ),
    ]
