# Generated by Django 4.1.5 on 2023-01-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_member_memberimg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="memberImg",
            field=models.CharField(default="img/member.png", max_length=20),
        ),
    ]
